services:
  # Base de données MySQL partagée
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PHP Service 1
  php1:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: php_service_1
    volumes:
      - app1_data:/var/www/html
    networks:
      - app_network
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - RUN_MIGRATIONS=true
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel App
    depends_on:
      mysql:
        condition: service_healthy
      mailhog:
        condition: service_started

  # PHP Service 2
  php2:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: php_service_2
    volumes:
      - app2_data:/var/www/html
    networks:
      - app_network
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel App
    depends_on:
      mysql:
       condition: service_healthy
      mailhog:
        condition: service_started
  # Nginx Service 1
  nginx1:
    image: nginx:alpine
    container_name: nginx_server_1
    ports:
      - "8001:80"
    volumes:
      - app1_data:/var/www/html:ro
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=Host(`serveur1.localhost`)"
      - "traefik.http.routers.nginx1.entrypoints=web"
      - "traefik.http.services.nginx1.loadbalancer.server.port=80"
  # Nginx Service 2
  nginx2:
    image: nginx:alpine
    container_name: nginx_server_2
    ports:
      - "8002:80"
    volumes:
      - app2_data:/var/www/html:ro
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`serveur2.localhost`)"
      - "traefik.http.routers.nginx2.entrypoints=web"
      - "traefik.http.services.nginx2.loadbalancer.server.port=80"
  # mail
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  
      - "1025:1025"   
    networks:
      - app_network

  #Traefik
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  app1_data:
  app2_data:



